

try{
    let =0;
    console.log(program)
    console.log("Program run successfully")
}

catch(err){
    console.log("This is an err")
    console.log(p)
}


finally{
    console.log("I am a good boy")
}